### PR TITLE
Adding shortcut for bash

### PR DESCRIPTION
**Pull request by mrhockeymonkey**
I have started moving a lot of our Invoke-Build scripts to Linux and Powershell 7. I have found this shortcut a great time saver for my purposes. Any objections to adding it in with this module. I added `.gitattributes` to preserve the correct line endings.

### CODE REVIEW

**Comment by nightroman** [comment]
I am not an expert in this sort of things but it all looks good, I will merge it and make sure the new file is in the package.

Is it the requirement that command lines use lower case name? I'd like to preserve the original case.

**Comment by nightroman** [comment]
> Is it the requirement that command lines use lower case names? I'd like to preserve the original case (as defined, documented, etc.).

OK, I assume it is not the requirement and amend the names. Correct me if I am wrong. I have no Linux in any form to test the change.

**Comment by nightroman** [comment]
Another question. Why `-nologo` and `-noninteractive` ? Do you see any difference without them? Otherwise I remove them.

**Comment by nightroman** [comment]
v5.5.9

**Comment by mrhockeymonkey** [comment]
You are correct case shouldn't matter. `-nologo` and `-noninteractive` can also be dropped they were just preferences. Thanks for merging!

**Pull request merged**
