### PR TITLE
Support installation folders other than in Program Files

### PR DESCRIPTION
**Pull request by Nuklon**
At the moment, VS installations must recide in the Program Files (x86) folder. If it's installed in another location, then the path isn't resolved anymore. This uses vswhere, which is always installed on the same location), and uses the given paths. This now correctly resolves a path on another drive.

### CODE REVIEW

**Comment by Nuklon** [comment]
My PS skills are a little rusty, so I might not have done everything correctly, but it's working now here.

**Comment by nightroman** [comment]
Thank you... But instead of `vswhere` we are supposed to use the PowerShell module `VSSetup` and this is already supported and documented. From `Resolve-MSBuild` help:

```
    For MSBuild 15+ the command uses the module VSSetup, see PSGallery.
    If VSSetup is not installed then the default locations are used.
    VSSetup is required for not default installations.
```

Why do we need another tool?

**Comment by Nuklon** [comment]
I've not seen that, then this is probably not necessary.

**Comment by nightroman** [comment]
No problem!
`VSSetup` is really better for PowerShell.

**Pull request closed without merging**
