### PR TITLE
Extend Show-BuildGraph

### PR DESCRIPTION
**Pull request by Szeraax**
* Added new Parameter -DisplayNumbers to allow choosing for numbers to be shown on lines, nodes, or both. 
* Added new node shape if task contains conditional logic (Diamond)

### CODE REVIEW

**Comment by nightroman** [comment]
Thank you. Let me play with this in another branch BuildGraph.

**Comment by Szeraax** [comment]
I'm an idiot, but I am concerned that iterating thorugh $all.Values doesn't clean $GraphvizNode. Maybe it doesn't matter, but maybe need `$GraphvizNode = ''` on Line 128.

**Comment by nightroman** [comment]
Don't worry, I'll review and take care of everything.

I like diamonds for conditional tasks. Not sure why you use `switch` and how it
works or even correct. E.g. you are comparing with a `[string] "True"` in the
first case, why? I will change this to simple clear `if else`.

I have doubts about `$DisplayNumbering`. I think one either wants to see
numbers or not. And if he does then all numbers matter, not just "order"
or "owned". Please explain the value of such customization (which also
adds complexity to the interface).

**Comment by nightroman** [comment]
> I am concerned that iterating thorugh $all.Values doesn't clean $GraphvizNode
Yes, I think so, too. Don't worry, I'll take care.

**Comment by nightroman** [comment]
Hmm, about the diamonds... We can only be sure `If` has a condition if it is a scriptblock or not equal to `$true`. But if it is `$true` then it is either the default or evaluated, can be either of two.

**Comment by Szeraax** [comment]
What do you mean on that conditional? When I look at $all.Values, I see my condition before evaluating: https://imgur.com/a/JH58mI8

Also, here's my build path that uses a conditional (Only publish during default build if $Message)

**Comment by Szeraax** [comment]
Oh, but in my version of the script, it only displays the task order if there more than 2 tasks (self and another). I think it comes out pretty clean while showing the order of my tasks.

**Comment by nightroman** [comment]
```
task withCondition -If (1 -eq 1) {}
task noCondition {}
```
Both are shown as boxes even though `withCondition` has a condition. That's what I mean.

**Comment by Szeraax** [comment]
> 
> 
> Don't worry, I'll review and take care of everything.
> 
> I like diamonds for conditional tasks. Not sure why you use `switch` and how it
> works or even correct. E.g. you are comparing with a `[string] "True"` in the
> first case, why? I will change this to simple clear `if else`.
> 
> I have doubts about `$DisplayNumbering`. I think one either wants to see
> numbers or not. And if he does then all numbers matter, not just "order"
> or "owned". Please explain the value of such customization (which also
> adds complexity to the interface).

I used switch because I was thinking that there be other shapes that may be good to use for other things, but as I looked at the list (https://graphviz.gitlab.io/_pages/doc/info/shapes.html), I didn't see any that I could immediately make use of, if-else seems fine to me. I'll test that conditional more, since I swear that it is working for me, but could be crazy. 

DisplayNumbering serves only to allow further customization without breaking backwards compatibility. You may well be right about the use case. I won't be personally offended if you decide you don't want it. Its in my script that I use and I love it :)

**Comment by Szeraax** [comment]
> 
> 
> ```
> task withCondition -If (1 -eq 1) {}
> task noCondition {}
> ```
> 
> Both are shown as boxes even though `withCondition` has a condition. That's what I mean.

I see what you mean now. I've only done scriptblock conditions, How interesting!

**Comment by Szeraax** [comment]
Interesting: https://imgur.com/D2LsscN

**Comment by nightroman** [comment]
> DisplayNumbering serves only to allow further customization without breaking backwards compatibility. You may well be right about the use case. I won't be personally offended if you decide you don't want it. Its in my script that I use and I love it :)

> I think it comes out pretty clean while showing the order of my tasks.

I agree that `TaskOrder` gives somewhat cleaner picture. And yet I am not tempted to add a new parameter for this. Keeping things simple is important. But I think we can get the best of both if we change the current behavior to show just `TaskOrder`. The script, if any, is usually the last. And even if it is not than it can be inferred, the missing number stands for it.

**Comment by Szeraax** [comment]
Seems reasonable to me.

**Comment by nightroman** [comment]
Hi @Szeraax 
Please take a look at my changes. I think I addressed both issues. If all is fine I'll release this.

**Comment by Szeraax** [comment]
Couple things: 
* I notice that Show-BuildGraph is caps sensitive. I hope that's intentional since by default powershell isn't. 
* Shapes all look good. I like the ovals. 
* In my tests, everything worked great. 
* I liked your solution with Invoke-Build.
* I still like the idea of not numbering lines (edges?) if a task only paths to 1 other job a la 127: `if ($Number -and $it.Jobs.Count -gt 2) {`. See picture (may have already sent this) of comparison: https://imgur.com/SzaZJt2 . You can see that Init has 3 tasks. two are self and 1 is Clean-Workspace
** Alternatively, if it contains only 1 [string] and 1 [scriptblock] in `$it.Jobs`, then skip showing the numbers, but that may be overkill.
*** Ya, this is TINY. Super tiny. I like this change, but don't feel obligated to change this functionality :)

**Comment by nightroman** [comment]
> I notice that Show-BuildGraph is caps sensitive. I hope that's intentional since by default powershell isn't.

Please explain or give an example, I am not sure what it is.

As for not showing a number for a single link, I do not know... I actually want to see it. I like consistency. A missing number looks like a false note to me (OCD?).

**Comment by nightroman** [comment]
Talking about consistency. We do not cover two different shapes tasks with no scripts depending on `If`, they are all ovals. Maybe it's fine for now.

**Comment by Szeraax** [comment]
> 
> 
> > I notice that Show-BuildGraph is caps sensitive. I hope that's intentional since by default powershell isn't.
> 
> Please explain or give an example, I am not sure what it is.
> 
> As for not showing a number for a single link, I do not know... I actually want to see it. I like consistency. A missing number looks like a false note to me (OCD?).

https://imgur.com/Ld9jfUn

I have a task called Init and a task called init. Gets two separate task shapes. Also tested when init has a script block (causing it to be a square) and it still is separate from the task Init. 

Ya, you feel good about it to leave the numbering consistent, so I feel good about it. :)

**Comment by nightroman** [comment]
> I have a task called Init and a task called init. Gets two separate task shapes.

I have no idea how this is possible. Might be a bug or something else. I need a script to investigate.

**Comment by nightroman** [comment]
Never mind, I built an example. I'll take a look.

**Comment by Szeraax** [comment]
Ha, was just about to send you:

```
Add-BuildTask Init
Add-BuildTask init
Add-BuildTask . Init
```

**Comment by nightroman** [comment]
OK, I have found the reason and fixed it as well. I will release later today or tomorrow.

**Comment by Szeraax** [comment]
Sounds awesome! Thanks for your amazing module and especially for this visualization tool!

**Pull request merged**
