### PR TITLE
automatic var ($_) causes StrictMode exception

### PR DESCRIPTION
**Pull request by uw-dc**
https://github.com/nightroman/Invoke-Build/issues/190

### CODE REVIEW

**Comment by nightroman** [comment]
@uw-dc Have you read my comments? I cannot reproduce and do not understand the issue.

**Comment by nightroman** [comment]
NB All internal variables of IB should be `${*xyz}`.

**Comment by uw-dc** [comment]
Would ${*SessionState} be a preferred way to assign / reference this variable?

**Comment by nightroman** [comment]
> Would ${*SessionState} be a preferred way to assign / reference this variable?

Let's find out what is going on first, then think about the PR.

**Pull request closed without merging**
