### PR TITLE
Show-BuildGraph : Update used viz.js version

### PR DESCRIPTION
**Pull request by Outlivier**
Not a very usefull Pull-Request : 

* Update used viz.js version from 1.8.0 to 2.1.2
* Use a CDN instead of a direct GitHub URL.
* The version 2.1.2 changed the following :
    * Requires two javascript files : `viz.js` and `lite.render.js` => the JS parameter must be * or the path to a directory containing those files
    * [Usage](https://github.com/mdaines/viz.js/wiki/Usage) is a little different, must use the `renderSVGElement` that return a promise.

### CODE REVIEW

**Comment by Outlivier** [comment]
Note : It's a breaking change for people using `-File "mydirectory\viz.lite.js"`, must update javascript files and use `-File "mydirectory"`

**Comment by nightroman** [comment]
Thank you for your help. I was about to do this, too.
I will merge and follow up shortly.

**Comment by nightroman** [comment]
@Outlivier What was the reason for the upgrade? Just out of curiosity. If it's just to keep things up-to-date, it's perfectly fine, very good. I just would like to know if it is something "more interesting".

**Comment by Outlivier** [comment]
It's only to keep things up-to-date. I have currently a script to build a dependency graph for visual studio solution which use https://yuml.me. The output of this script is not great at all when we start to have lot of dependencies. I thought your solution with viz.js is way better, so in order to change my dependency graph script, i checked if it easy to use the last version to avoid future upgrade.

**Comment by nightroman** [comment]
I tweaked some styling and removed the alias `%`.
Thank you for your help, you basically did my job, perfectly!

**Pull request merged**
